version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      python-deps:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    reviewers:
      - ionicsolutions
    assignees:
      - ionicsolutions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-deps:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    reviewers:
      - ionicsolutions
    assignees:
      - ionicsolutions
