name: Train Model

on:
  workflow_dispatch:
    inputs:
      criterion:
        description: "The function to measure the quality of a split:"
        default: gini
        type: choice
        options:
          - gini
          - entropy
          - log_loss
      max-depth:
        description: "The maximum depth of the tree:"
        type: number
        default: 5
      min-samples-split:
        description: "The minimum number of samples required to split an internal node:"
        type: number
        default: 2
      min-samples-leaf:
        description: "The minimum number of samples required to be at a leaf node:"
        type: number
        default: 1
      max-leaf-nodes:
        description: "The maximum number of leaf nodes in the tree:"
        type: number
        default: 5

jobs:
  train:
    runs-on: ubuntu-latest
    environment: Neptune
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
           pip install --upgrade pip
           pip install -r requirements.txt

      - name: Train model
        env:
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
          NEPTUNE_PROJECT: ${{ vars.NEPTUNE_PROJECT }}
        run: |
          python train.py \
            --criterion ${{ github.event.inputs.criterion }} \
            --max-depth ${{ github.event.inputs.max-depth }} \
            --min-samples-split ${{ github.event.inputs.min-samples-split }} \
            --min-samples-leaf ${{ github.event.inputs.min-samples-leaf }} \
            --max-leaf-nodes ${{ github.event.inputs.max-leaf-nodes }}
